/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.test.java.celeste;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        assertEquals(true, true);
    }
}
